### PR TITLE
Made some minor modifications to the documentation to clarify some aspects a bit more

### PR DESCRIPTION
**Pull request by bbbart**
Hi Jeff,

here's my proposal for some documentation changes.

If you're up for it, I can also put every sentence on its own line in the `.rst` files. This will minimise the git diffs in future changes to the documentation.

It might also be interesting to add a Makefile to the `/docs` directory to generate the documentation with a simple `make` command. I can do that too, if interested.

### CODE REVIEW

**Comment by dairiki** [comment]
Thank you!  These are all good improvements.

Wow.  Who knew there were that many typos in my original?  It always helps to have a second set of eyes look over one's writing.

I've just added a `docs` environment to the top-level `tox.ini` which builds the HTML docs (with "nit-picky mode" enabled).
```
tox -e docs
```
should now build the docs, with output in `.tox/docs/tmp/html_docs`.  (I've just pushed that to master.)

That should obviate some of the need for a Makefile.  If you'd still like to add a simple one, go ahead.

**Comment by bbbart** [comment]
Here are some extra additions to the PR.

I think the addition to `tox.ini` is more elegant than the proposed Makefile-solution, so I dropped that. :-)

**Comment by dairiki** [comment]
This is excellent!  Thank you very much.

**Comment by bbbart** [comment]
my pleasure!

**Pull request merged**
